config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :trips, only: [:index, :show]
  namespace :traveler do
    resources :trips, only: [:new, :create, :show] do
      resources :destinations, only: [:new, :create, :show] do
        resources :journals, only: :create
        resources :photos, only: :create
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :trip
  has_many :photos
  has_many :journals
  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true
  validates :address, presence: true
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  belongs_to :destination
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :destinations
  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips
  has_many :journals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :authenticate_user!

  def create
    @destination = Destination.find(params[:destination_id])
    @destination.journals.create(journal_params.merge(user: journal_user))
    redirect_to traveler_trip_destination_path(@destination)
  end

  private

  def journal_params
    params.require(:journal).permit(:entry)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end
  
end

app/controllers/test_trips_controller.rb
class TestTripsController < ApplicationController
  def index 
  end
  
end

app/controllers/traveler/destinations_controller.rb
class Traveler::DestinationsController < ApplicationController

  def new
    @trip = Trip.find(params[:trip_id])
    @destination = Destination.new
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @destination = @trip.destinations.create(destination_params)
    redirect_to traveler_trip_path(@trip)
  end

  def show
    @destination = Destination.find(params[:id])
    @trip = Trip.find(params[:trip_id])
    @journal = Journal.new
  end


  private

  def destination_params
    params.require(:destination).permit(:name, :address)
  end
end

app/controllers/traveler/journals_controller.rb
class Traveler::JournalsController < ApplicationController
  before_action :authenticate_user!

  def create
    @destination = Destination.find(params[:destination_id])
    @destination.journals.create(journal_params.merge(user: current_user))
    redirect_to traveler_trip_destination_path(params[:trip_id], params[:destination_id])
  end

  private

  def journal_params
    params.require(:journal).permit(:entry)
  end
end

app/controllers/traveler/trips_controller.rb
class Traveler::TripsController < ApplicationController
  before_action :authenticate_user!

  def new
    @trip = Trip.new
  end

  def create
    @trip = current_user.trips.create(trip_params)
    if @trip.valid?
      redirect_to traveler_trip_path(@trip)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @trip = Trip.find(params[:id])

    @destinations = @trip.destinations

    @sum_coords = { lat: 0, lng: 0 }  

    @destinations.each do | destination |
      @sum_coords[:lat] = @sum_coords[:lat] + destination.latitude
      @sum_coords[:lng] = @sum_coords[:lng] + destination.longitude
    end

     @average_coords = {
       lat: @sum_coords[:lat]/@destinations.count,
       lng: @sum_coords[:lng]/@destinations.count
     }
   end

  private

  def trip_params
    params.require(:trip).permit(:name, :description, :address)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
  end

  def create
    Trip.create(trip_params)
    redirect_to root_path
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def marker
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :description, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test_trips_helper.rb
module TestTripsHelper
end

app/helpers/traveler/destinations_helper.rb
module Traveler::DestinationsHelper
end

app/helpers/traveler/trips_helper.rb
module Traveler::TripsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>DETOUR HOME</h1>
    <br />
    <br />
    <div class="row">
      <div class="col-12 col-sm">
        <%= link_to 'Start A New Journey', new_traveler_trip_path , class: 'btn btn-success' %>
      </div>

      <br /><br />
      <div class="col-12 col-sm">
        <%= link_to 'Manage A Journey', trips_path, class: 'btn btn-success' %>
      </div>
    </div>
    <br /><br />
    <br />

  </div>
</div>

app/views/traveler/destinations/new.html.erb
<div class="booyah-box-b col-10 offset-1 text-center">
  <div class="hero-a">
    <div class="booyah-box frosty col-10 offset-1">
      <h1>Add a new Destination</h1>
      <%= simple_form_for @destination, url: traveler_trip_destinations_path(@trip) do |f|%>
        <%= f.input :name %>
        <%= f.input :address %>
        <br />
        <%= f.submit "Add Destination", class: 'btn btn-primary' %>
        <br />
        <br />
      <% end %>
    </div>
  </div>
</div>

app/views/traveler/destinations/show.html.erb
<div class="hero-a booyah-box-c col-10 offset-1 text-center">
  <div class="booyah-box-c frosty col-10 offset-1 text-center">
    <h4><%= @trip.name %></h4>
    <hr />
    <h6><%= @trip.description %></h6>
    <hr />
    <h3><div class="col-sm-8 offset-2 text-center"><%= link_to @destination.name, traveler_trip_destination_path, class: 'text-center' %></div></h3>
  </div>



  <div class="booyah-box-b frosty col-10 offset-1 text-center">
    <!DOCTYPE html>
    <html>
      <head>
        <title>Simple Map</title>
        <meta name="viewport" content="initial-scale=1.0">
        <meta charset="utf-8">
        <style>
          /* Always set the map height explicitly to define the size of the div
           * element that contains the map. */
          /* Optional: Makes the sample page fill the window. */
          html, body {
            height: 100%;
            margin: 0;
            padding: 0;
          }
        </style>
      </head>
      <body>
        <div id="map"></div>
        <script>
          var coordinates = {lat: <%= @destination.latitude %>, lng: <%= @destination.longitude %>};
//above defines the variable coordinates
          var map;
          function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
              center: coordinates,
              zoom: 8
//need to look into whether i can remove zoom.  zoom could prevent all markers from appearing
            });
//builds the map and centers on the coordinates
          var marker = new google.maps.Marker({position: coordinates, map: map});
          }
//adds a marker where the coordinate is
        </script>

        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAOE-HGxJJ-LkvmoPg55T4NfiHutZ_fZG0&callback=initMap">
        </script>
      </body>
      </html>
    </div>
  </div>





  <div class="clear"></div>

  <div class="booyah-box-b frosty col-10 offset-1 text-center">
    <%= simple_form_for @journal, url: traveler_trip_destination_journals_path(@trip, @destination) do |f| %>
      <div class="booyah-box-b frosty">
        <%= f.input :entry %>
        <%= f.submit "Add a Journal Entry", class: 'btn btn-primary' %>
      </div>
    <% end %>

    <div class="booyah-box-b frosty ">
      <% @destination.journals.each do |journal| %>
      <div>
        <blockquote>
          <b><%= journal.entry %></b>
            <small><%= journal.created_at %></small>
        </blockquote>
      </div>
      <% end %>
    </div>
  </div>

app/views/traveler/trips/index.html.erb
<div class="booyah-box-b col-10 offset-1 text-center">
  <div class="hero-a">
    <div class="booyah-box-b frosty col-10 offset-1 text-center">
      <% @trips.each do |trip| %>
        <div class="booyah-box frosty col-10 offset-1">
          <h1><%= link_to trip.name, traveler_trip_path(trip) %></h1>
          <br />
          <i><%= trip.address %></i><br />
          <p><%= trip.description %></p><br />

          <% if trip.user.present? %>
            <small><%= trip.user.email %></small>
          <% end %>
        </div>
        <hr />
      <% end %>
    </div>
  </div>
</div>

app/views/traveler/trips/new.html.erb
<div class="booyah-box-b col-10 offset-1 text-center">
  <div class="hero-a">
    <div class="booyah-box-b frosty col-10 offset-1 text-center">
      <h1>Go On A New Journey</h1>

      <%= simple_form_for @trip, url: traveler_trips_path, html: {id: 'newTripForm' }  do |f| %>
          <div class="frosty col-10 offset-1">
          <div class="form-inputs">
            <%= f.input :name %>
            <%= f.input :description %>
            <br />
            <%= f.submit 'Create', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
      <br />
      <br />
      <br />
      <br />
    </div>
  </div>
</div>

app/views/traveler/trips/show.html.erb
<br />
<div class="booyah-box-b col-10 offset-1 text-center">
  <div class="hero-a">
    <div class="booyah-box frosty col-10 offset-1">
      <h1 class="text-center"><%= @trip.name %></h1>
      <hr />
      <h5 class="text-center"><%= @trip.description %></h5>
    </div>
  </div>

  <div class="booyah-box-b frosty col-10 offset-1 text-center">
    <!DOCTYPE html>
    <html>
      <head>
        <title>Simple Map</title>
        <meta name="viewport" content="initial-scale=1.0">
        <meta charset="utf-8">
        <style>
          html, body {
            height: 100%;
            margin: 0;
            padding: 0;
          }
        </style>
      </head>
      <body>
        <div id="map"></div>
        <script>
          var averageCoordinates = {
            lat: <%= @average_coords[:lat] %>,
            lng: <%= @average_coords[:lng] %>
          };

          var googleMap;
          function initMap() {
            googleMap = new google.maps.Map(document.getElementById('map'), {
              center: averageCoordinates,
              zoom: 6
            });

            var marker = {};
            var markerCoordinates = {};
            
              <% @destinations.each do | destination | %>
                markerCoordinates = {
                  lat: <%= destination.latitude %>,
                  lng: <%= destination.longitude %>   
                };
                
                marker = new google.maps.Marker({
                  position: markerCoordinates,
                  map: googleMap
                });
            <% end %>
          }
        </script>

        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAOE-HGxJJ-LkvmoPg55T4NfiHutZ_fZG0&callback=initMap">
        </script>
      </body>
    </html>
  </div>


    <hr />
    <br />
    <div class="row col-10 offset-1 text-center">
      <div class="col-12 col-sm text-center">
        <%= link_to 'Preview Trip Page', trip_path(@trip), class: 'btn btn-primary btn-sm'%>
      </div>
      <br />
      <div class="col-12 col-sm text-center ">
        <%= link_to 'Add a New Destination', new_traveler_trip_destination_path(@trip), class: 'btn btn-primary btn-sm' %>
        <br />
        <br />
      </div>
    </div>

    <ul>
      <% @trip.destinations.each do |destination| %>
        <div class="row frosty booyah-box-c col-12 col-sm"> 
          <h5 class="col-12 text-center"> <%= link_to destination.name, traveler_trip_destination_path(@trip, destination) %></h5>
        </div>
          <br />
      <% end %>
    </ul>
  </div>
</div>

app/views/trips/index.html.erb
  <div class="hero-a booyah-box-b col-10 offset-1">
    <div class="booyah-box-b frosty col-10 offset-1 text-center">
      <h1 class="text-center">All My Journies</h1>
      <% @trips.each do |trip| %>
        <div class="booyah-box-b frosty link col-10 offset-1">
          <h2 class="text-center link">
            <%= link_to trip.name, trip_path(trip) %>
          </h2>
          <br />
          <div class="row">
            <div class="col-sm-8 col-12">
              <%= trip.description %>
              <br />
            </div>
            <div class="col-sm-4 col-12 text-center">
              <%= link_to 'More Details', trip_path(trip), class: 'btn btn-primary btn-large' %>
              <br />
              <br />
              <%= link_to 'Administer', traveler_trip_path(trip), class: 'btn btn-danger btn-large' %>
            </div>
          </div>
          <br class="clr" />
        </div>
      <% end %>
    </div>
  </div>

app/views/trips/new.html.erb
<h1>New Trip</h1>

app/views/trips/show.html.erb
<div class="hero-a booyah-box-b col-10 offset-1 text-center">
  <div class="booyah-box-b frosty col-10 offset-1 text-center">
    <h1><%= @trip.name %></h1>
    <hr />
    <div class="col-sm-8 col-12 offset-2 text-center">
      <%= @trip.description %>
    </div>
    <hr />
    <ul>
      <% @trip.destinations.each do |destination| %>
        <div class="row frosty booyah-box-c col-12"> 
          <h5 class="col-12 text-center"> <%= link_to destination.name, traveler_trip_destination_path(@trip, destination) %></h5>
        </div>
      <% end %>
    </ul>
    <% if current_user && current_user == @trip.user %>
      <br />
      <%= link_to 'Administer', traveler_trip_path(@trip), class: 'btn btn-danger btn-large' %>
    <% end %>
  </div>
</div>